### ISSUE TITLE
Separate button for Play & Pause

### ISSUE THREAD

**Issue by SubhrajyotiSen** [SEAbdulbasit/MusicApp-KMP#16]
Right now the app seems to be using the same icon for both playing and paused state (https://developer.android.com/reference/kotlin/androidx/compose/material/icons/Icons.Filled#(androidx.compose.material.icons.Icons.Filled).PlayArrow())

It'll be easier to understand if different icons were used for the playing and paused state.

Note: I've verified this only on Web target and then checked the code.

**Comment by Sushant-Hande** [comment]
> @Sushant-Hande can you look into the pause and play icons? Currently we have 1 icon for both states.

@SEAbdulbasit Sure, I will look into play and pause icons.

**Comment by Sushant-Hande** [comment]
@SEAbdulbasit and @SubhrajyotiSen
I have opened the above pull request to address this issue. Please review it and if the fix looks good then we are good to close this issue.
