### ISSUE TITLE
Update Kotlin and dependencies

### ISSUE THREAD

**Issue by pahill** [SEAbdulbasit/MusicApp-KMP#18]
Hi there!

Please, could you update your dependencies and Kotlin version? Your sample is on [our samples page](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-samples.html) and we'd love it if you could keep it updated.

Thank you so much,
Pamela
Kotlin Developer Advocate @ JetBrains

**Comment by SEAbdulbasit** [comment]
Hi Pamela
Yes, updating all the libs and versions.
